py -m pip install datetime 
py -m pip install turtle
py -m pip install sys
py -m pip install time
py -m pip install pygame
py -m pip install pygame 
py -m pip install turtle
py -m pip install time py 
py -m pip install datetime 
py -m pip install googletrans 
py -m pip install tkinter 
py -m pip install pygame 
py -m pip install speechrecognition
py -m pip install tkinter 
py -m pip install math
py -m pip install pygame 
py -m pip install speechrecognition
py -m pip install playsound==1.2.2
py -m pip install speechrecognition 
py -m pip install os
py -m pip install os
py -m pip install time
py -m pip install playsound==1.2.2
py -m pip install speechrecognition 
py -m pip install gtts 
py -m pip install random
py -m pip install pandas 
py -m pip install sendgrid
py -m pip install sendgrid
py -m pip install sendgrid
py -m pip install os
py -m pip install math
py -m pip install webbrowser
py -m pip install time

py -m pip install wikipedia
py -m pip install datetime
py -m pip install json
py -m pip install pygame
py -m pip install random
py -m pip install re
py -m pip install webbrowser
py -m pip install smtplib
py -m pip install requests
py -m pip install urllib
py -m pip install urllib
py -m pip install selenium 
py -m pip install selenium
py -m pip install webdriver_manager
py -m pip install time
py -m pip install gtts 
py -m pip install youtube_search 
py -m pip install selenium 
py -m pip install selenium
py -m pip install webdriver_manager
py -m pip install time 
py -m pip install gtts 
py -m pip install tkinter 
py -m pip install youtube_search
py -m pip install json
py -m pip install spotipy.oauth2 
py -m pip install spotipy
py -m pip install pyaudio
py -m pip install playsound==1.2.2
py -m pip install os
py -m pip install ytmusicapi
py -m pip install google-api-python-client
py -m pip install youtube_dl
py -m pip install json
py -m pip install spotipy
py -m pip install spotify
from spotipy.oauth2 
py -m pip install webbrowser
py -m pip install pyaudio
